pipeline {
    agent any

    environment {
        REGISTRY  = "prajwals0209"
        SERVICE_NAME = "app"
	COMMIT_ID = "${env.GIT_COMMIT}"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Login to DockerHub'){
	   steps{
		withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh 'echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin'
                }
           }
        }

        stage('Docker Build') {
            steps {
                sh "docker build  -f PDS/Dockerfile  -t $REGISTRY/$SERVICE_NAME:latest ."
		sh "docker tag $REGISTRY/$SERVICE_NAME:latest $REGISTRY/$SERVICE_NAME:$COMMIT_ID"
		echo "Built and retagged with 'latest' and '$COMMIT_ID' successfully"
            }
        }

        stage('Docker Push') {
            steps {
                sh "docker push $REGISTRY/$SERVICE_NAME:latest"
		sh "docker push $REGISTRY/$SERVICE_NAME:$COMMIT_ID"
		echo "$SERVICE_NAME image pushed to private registry with 'latest' and '$COMMIT_ID' as tags successfully"
            }
        }
        stage('Kubernetes Deploy') {
            steps {
	      withCredentials([file(credentialsId: 'kubeconfig-file', variable: 'KUBECONFIG')]) {
                sh '''
                kubectl --kubeconfig="$KUBECONFIG" rollout restart deployment/"$SERVICE_NAME"-deployment
                '''
                echo "${SERVICE_NAME} deployed successfully"
              }
            }
        }
    }
}

